name: Run PHP Script and Commit Changes

on:
  schedule:
    - cron: '0 0 * * *' # اجرای هر روز ساعت 12:00 بامداد به وقت UTC
  workflow_dispatch: # امکان اجرای دستی از GitHub

jobs:
  run-php-script:
    runs-on: ubuntu-latest  # سیستم عامل مورد استفاده

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # دریافت کد از مخزن

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # نسخه PHP مورد نظر

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Run PHP script
        run: |
          php bot.php  # اجرای اسکریپت PHP

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "YourGitHubUsername"
      
      - name: Commit changes and push
        env:
          FARSHID_TOKEN: ${{ secrets.FARSHID_TOKEN }}  # استفاده از Token در محیط متغیرها
        run: |
          git add previous_links.txt
          git commit -m "Update previous links"
          git push https://github.com/bia2mafya/freeev2ray-bot.git HEAD:main  # ارسال به مخزن با استفاده از FARSHID_TOKEN
