name: Run PHP Script and Commit Changes

on:
  schedule:
    - cron: '0 0 * * *' # اجرای هر روز در نیمه‌شب UTC
  workflow_dispatch:

jobs:
  run-php-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Run PHP script
        run: |
          php bot.php

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "YourGitHubUsername"

      - name: Commit changes and push
        env:
          FARSHID_TOKEN: ${{ secrets.FARSHID_TOKEN }}
        run: |
          git add previous_links.txt
          git commit -m "Update previous links"
          git push https://$FARSHID_TOKEN@github.com/bia2mafya/freeev2ray-bot.git HEAD:main
